name: Build pip package

on:
  push:
    branches:  [ master ]
  pull_request:
    branches:  [ master ]

jobs:
  build:
    timeout-minutes: 8
    runs-on: ubuntu-latest
    env:
      working-dir: "."
    strategy:
      matrix:
        python-version: [3.7]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install gtk-3
        run: |
          sudo apt install libgtk-3-dev

      - name: Pip install
        working-directory: ${{ env.working-dir }}
        run: |
          pip install git-python
          pip install -U \
              -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-16.04 \
                  wxPython
          pip install ${{ env.working-dir }}
