name: Build pip package

on:
  pull_request:
    paths:
      - "*"

jobs:
  build:
    timeout-minutes: 8
    runs-on: ubuntu-latest
    env:
      working-dir: "."
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Pip install
        working-directory: ${{ env.working-dir }}
        run: pip install ${{ env.working-dir }}
